import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,readFile,mkdir,rm,realpath,stat} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {execFileSync} from 'node:child_process';import {createHash,randomUUID} from 'node:crypto';import {applyDependencyPatch,recoverDependencyTransaction} from '../lib/dependency-transaction.mjs';
const hash=x=>createHash('sha256').update(x).digest('hex');
async function fixture(){
 const dir=await realpath(await mkdtemp(join(tmpdir(),'mithril-transaction-'))),git=args=>execFileSync('git',args,{cwd:dir,stdio:'pipe'}).toString().trim();
 const files=['package.json','package-lock.json'].map((path,i)=>({path,text:JSON.stringify({fixture:i,version:1})}));for(const f of files)await writeFile(join(dir,f.path),f.text);
 git(['init']);git(['add',...files.map(f=>f.path)]);git(['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-m','fixture']);
 const head=git(['rev-parse','HEAD']),lock=join(dir,'.git/mithril-dependency-transaction');
 const j={version:1,directory:dir,head,files:files.map(f=>({path:f.path,previous:f.text,next:f.text.replace('"version":1','"version":2'),before_sha256:hash(f.text),after_sha256:hash(f.text.replace('"version":1','"version":2')),mode:0o600,temp:'.mithril-upgrade-'+randomUUID()}))};
 const patch={status:'verified_dependency_patch',base:j.files.map(f=>({path:f.path,sha256:f.before_sha256})),files:j.files.map(f=>({path:f.path,text:f.next,sha256:f.after_sha256}))};
 async function pending(pid=2147483000){await mkdir(lock,{mode:0o700});await writeFile(join(lock,'owner.json'),JSON.stringify({pid}),{mode:0o600});await writeFile(join(lock,'journal.json'),JSON.stringify(j),{mode:0o600});}
 return {dir,git,head,lock,j,patch,pending,dispose:()=>rm(dir,{recursive:true,force:true})};
}
test('exclusive apply blocks concurrent calls and leaves no recovery state on success',async()=>{const f=await fixture();try{const r=await Promise.allSettled([applyDependencyPatch(f.dir,f.patch),applyDependencyPatch(f.dir,f.patch)]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.match(r.find(x=>x.status==='rejected').reason.message,/transaction_pending|clean_project/);assert.equal(f.git(['rev-parse','HEAD']),f.head);await assert.rejects(stat(f.lock),{code:'ENOENT'});}finally{await f.dispose();}});
test('interrupted half-write and fully-written but unfinalized transactions recover original pair',async()=>{for(const count of [1,2]){const f=await fixture();try{await f.pending();for(const e of f.j.files.slice(0,count))await writeFile(join(f.dir,e.path),e.next);await assert.rejects(applyDependencyPatch(f.dir,f.patch),/transaction_pending/);const r=await recoverDependencyTransaction(f.dir);assert.equal(r.status,'dependency_transaction_recovered');assert.equal(r.restored_files,count);for(const e of f.j.files)assert.equal(await readFile(join(f.dir,e.path),'utf8'),e.previous);await assert.rejects(stat(f.lock),{code:'ENOENT'});}finally{await f.dispose();}}});
test('operator changes refuse recovery without partially restoring another file',async()=>{const f=await fixture();try{await f.pending();await writeFile(join(f.dir,f.j.files[0].path),f.j.files[0].next);await writeFile(join(f.dir,f.j.files[1].path),'operator edit');await assert.rejects(recoverDependencyTransaction(f.dir),/recovery_required/);assert.equal(await readFile(join(f.dir,f.j.files[0].path),'utf8'),f.j.files[0].next);assert.equal(await readFile(join(f.dir,f.j.files[1].path),'utf8'),'operator edit');assert.equal((await stat(join(f.lock,'journal.json'))).mode&0o777,0o600);}finally{await f.dispose();}});
test('active owner and altered journal or Git HEAD refuse recovery',async()=>{for(const kind of ['active','digest','head']){const f=await fixture();try{await f.pending(kind==='active'?process.pid:2147483000);if(kind==='digest'){f.j.files[0].previous='forged';await writeFile(join(f.lock,'journal.json'),JSON.stringify(f.j));}if(kind==='head')f.git(['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','--allow-empty','-m','other operator commit']);await assert.rejects(recoverDependencyTransaction(f.dir),/transaction_active|recovery_evidence|recovery_scope/);for(const e of f.patch.base)assert.equal(hash(await readFile(join(f.dir,e.path),'utf8')),e.sha256);}finally{await f.dispose();}}});

test('CLI apply preflight rejects dirty project before inventory/feed evaluation',async()=>{const f=await fixture();try{await writeFile(join(f.dir,'package.json'),'operator edit');const r=execFileSync(process.execPath,[new URL('../bin/mithril-upgrade.mjs',import.meta.url).pathname,'--stdin','--apply-dir',f.dir],{input:JSON.stringify({files:f.patch.base}),stdio:['pipe','pipe','pipe']});assert.fail('must refuse');}catch(e){assert.equal(JSON.parse(e.stdout.toString()).error,'upgrade_clean_project_required');}finally{await f.dispose();}});

test('recovery CLI restores journal-backed partial write with no input/feed/model calls',async()=>{const f=await fixture();try{await f.pending();await writeFile(join(f.dir,f.j.files[0].path),f.j.files[0].next);const out=execFileSync(process.execPath,[new URL('../bin/mithril-upgrade.mjs',import.meta.url).pathname,'--recover-dir',f.dir],{stdio:['ignore','pipe','pipe']});const r=JSON.parse(out);assert.equal(r.ok,true);assert.equal(r.restored_files,1);assert.equal(f.git(['status','--porcelain']), '');}finally{await f.dispose();}});
test('second file replacement failure rolls back first and removes journal',async()=>{
 const f=await fixture();const fs=await import('node:fs');const {syncBuiltinESMExports}=await import('node:module');const original=fs.promises.rename;
 try{
  fs.promises.rename=async(a,b)=>{if(b===join(f.dir,'package-lock.json'))throw Object.assign(Error('controlled ENOSPC'),{code:'ENOSPC'});return original(a,b);};syncBuiltinESMExports();
  await assert.rejects(applyDependencyPatch(f.dir,f.patch),/controlled ENOSPC/);
  for(const e of f.j.files)assert.equal(await readFile(join(f.dir,e.path),'utf8'),e.previous);
  await assert.rejects(stat(f.lock),{code:'ENOENT'});
 }finally{fs.promises.rename=original;syncBuiltinESMExports();await f.dispose();}
});
